#关闭模板引擎的缓存
spring:
  thymeleaf:
    cache: false
  #配置文件放置的真实路径
  messages:
    basename: i18n.login
# 日期格式
  mvc:
    format:
      date: yyyy-MM-dd



server:
  #端口
  port: 80
  #虚拟目录
  servlet:
    context-path: /tian

