#关闭模板引擎的缓存
spring:
  thymeleaf:
    cache: false
  #配置文件放置的真实路径
  messages:
    basename: i18n.login
# 日期格式
  mvc:
    format:
      date: yyyy-MM-dd

  datasource:
    username: root
    password: suyan147258
    url: jdbc:mysql://localhost:3306/springboot?userUnicode=true&charcterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
#整合mybatis
mybatis:
  type-aliases-package: com.tian.pojo
  mapper-locations: classpath:com/tian/mapper/*.xml


server:
  #端口
  port: 80
  #虚拟目录
  servlet:
    context-path: /tian

